---
# See https://github.com/jvautier/project-cli
fullname: jvautier/docker-compose-vault
description: Docker-compose development stack with vault.
tags:
  - development
  - docker
  - docker-compose
  - vault
github:
  has_issues: true
  has_projects: false
  has_wiki: false
